# On Windows
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools-preview
# ```

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fust-ld=ldd"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-fust-ld=ldd"]
