name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  versioning:
    name: Toolchain Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: cargo --version --verbose
      - run: rustc --version
      - run: cargo clippy --version

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy -- -D warnings

  audit:
    name: Audit Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo audit

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release --verbose

  test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo test
        run: |
          cargo check
          cargo test --verbose

  tarpaulin:
    name: Calculate Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/checkout@v3
      - name: cargo check
        run: cargo check

      - name: run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "--ignore-tests"
